### ISSUE TITLE
Missed Packages

### ISSUE THREAD

**Issue by gigante** [fnando/sublime-text#3]
Some packages were removed from packagecontrol.io:
- SideBarEnhancements
- BufferScroll
- Dictionaries
- WordCount

**Comment by fnando** [comment]
Do you know why?

**Comment by fnando** [comment]
OK, I noticed that all repos are from @titoBouzout, but I don't know what's up. I added it to my own repository, so things should be fine.

**Comment by gigante** [comment]
I don't know why, but I decided to tell you anyway. You fixed quickly OK
